tighten/mailthief

src/MailThief.php
MailThief already implements the `queue()` and `later()` methods.
This just adds the contract to the class.
See issue #16
=> Implement Illuminate\Contracts\Mail\MailQueue

composer.json
Pulling in the entire Laravel Framework causes issues when trying to use this package in a Lumen application. These incompatibilities can be avoided by explicitly requiring only the necessary sub-packages, namely `illuminate/mail` and `illuminate/view`.
I have tested this with a fresh Lumen installation as well as an existing Lumen application.
=> Lumen support

src/Message.php, tests/MailThiefTest.php
Arr::first on Laravel 5.1 requires a callback, thanks to @T3chn0crat
and @amonger for bringing this up in PRs.
https://github.com/tightenco/mailthief/pull/23
https://github.com/tightenco/mailthief/pull/25
We don't want to use `array_shift` because it's destructive and using a filler callback seemed like not the best approach. Decided to copy `Arr::first`'s implementation and use `reset` instead.
=> Replace usage of `Arr::first` with native `reset`

readme.md, src/Testing/InteractsWithMail.php
Allows (slightly) simpler visibility to last message which is frequently
the basis of assertions related to mail.
=> Add lastMessage() to InteractsWithMail trait

src/MailThief.php
Initial 5.3 compatibility (#37), full Mailable support pending #30.
(Re-merging w/o squashing so #30's base isn't messed up)
=> Basic Laravel 5.3 compatibility (re-merge)

composer.json, src/MailThief.php, src/Support/MailThiefCollection.php, tests/InteractsWithMailTest.php, tests/MailThiefTest.php
As discussed in #37, our hope is to support old Laravel versions within the same package. This PR implements this for the updated @contains method in Laravel 5.3.
=> Implement custom collection class so we can standardize on `contains` implementation across Laravel versions

composer.json
Similar to #13, a full sample repo was created with Laravel 5.0 and MailThief tests successfully pass: https://github.com/besologic/mailthief-laravel-5.0
=> Add Laravel 5.0 support

src/MailThief.php, src/Testing/InteractsWithMail.php, tests/InteractsWithMailTest.php, tests/MailThiefTest.php
This PR adds a `subjects` method which simply collects all of the "stolen" message subjects. It also adds a method `seeInSubjects` which gives the ability to assert that certain subjects are inside a group of messages.
```php
$this->seeInSubjects("Invoice {$invoice->reference} from {$invoice->team->name}");
```
=> Add ability to get subjects and make assertions against a group of them

src/Testing/InteractsWithMail.php, tests/InteractsWithMailTest.php
I find myself in situations where other messages may have been sent after the one that I'm interested in making an assertion about. I can continue to have these locally, but they should be of more general use to others.
In particular, this should help with #53. The assertion methods may easily be rewritten to take advantage of these methods to become more general in which email gets matched.
=> Add Messages Accessors

src/Support/MailThiefCollection.php
With the release of Laravel 5.4 I got:
```
1) InteractsWithMailTest::test_get_messages
Declaration of MailThief\Support\MailThiefCollection::contains($key, $value = NULL) should be compatible with Illuminate\Support\Collection::contains($key, $operator = NULL, $value = NULL)
/home/thibaud/Code/mailthief/src/Support/MailThiefCollection.php:7
/home/thibaud/Code/mailthief/src/MailThief.php:25
/home/thibaud/Code/mailthief/tests/TestCase.php:52
/home/thibaud/Code/mailthief/tests/InteractsWithMailTest.php:25
ERRORS!
```
I just update the signature without changing the implementation because I think the only usage of `contains` in the source code is with only a closure or a value (one argument).
=> Update `contains` signature to match Laravel Support 5.4

src/MailThief.php
Closes #65
---
When attempting to catch the `reset password` email using Laravel 5.4, I get the following error.
```
Caused by
InvalidArgumentException: View [<html email>] not found. in /Users/username/app/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137
Stack trace:
#0 /Users/username/app/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\View\FileViewFinder->findInPaths('<!DOCTYPE html ...', Array)
#1 /Users/username/app/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\View\FileViewFinder->find('<!DOCTYPE html ...')
#2 /Users/username/app/vendor/tightenco/mailthief/src/MailThief.php(75): Illuminate\View\Factory->make('<!DOCTYPE html ...', Array)
#3 [internal function]: …
```
=> Issue #65: Fixing issue where HTML View throw an error.

src/Testing/InteractsWithMail.php
`$this->mailer->subjects()` raises Fatal Error when the mailer wasn't set explicitly.
Also, for consistency with the rest of the methods.
=> Call mailer getter in seeInSubjects

src/Testing/InteractsWithMail.php, tests/InteractsWithMailTest.php
Trait fix. method seeMessageFrom is incorrect in case when we set the sender name
=> Fix: trait method seeMessageFrom should work when from set with name

readme.md
Now that Laravel 5.3 is no longer new it's easier to direct the reader to the released HTML documentation.
=> link to Laravel documentation instead of source

src/Message.php, tests/MailThiefTest.php
The Laravel `message` class supports overwriting the recipient. This pull request brings support for that to MailThief.
https://laravel.com/api/5.4/Illuminate/Mail/Message.html#method_to
=> Support for overwriting the recipient

src/Testing/InteractsWithMail.php
This is a quick fix to account for older versions of phpunit (< v6) not being able to access $this->app before `setup()` is called by phpunit. Instead, the `hijackMail()` function now uses `method_exists()` for the `afterApplicationCreated()` function.
=> [Bugfix] Update InteractsWithMail to account for older versions of phpunit

src/Message.php, src/Testing/InteractsWithMail.php
Replaces calls to `collect` helper function with instances of `MailThiefCollection` which overrides the `Collection::contains` method.
Fixes https://github.com/tightenco/mailthief/issues/86
=> Make InteractsWithMail::getMessagesFor compatible with Laravel 5.2

src/Facades/MailThief.php
This is to address interoperability with MailThief and Lumen per issue #92. The check simply takes the first match and uses that to compare. This shouldn't cause any issues with Laravel or Lumen, and I've tested it with the version returned from Lumen and from Laravel. Both work with no issues.
=> Fix version issue with Lumen.

src/MailThief.php, tests/InteractsWithMailTest.php, tests/MailThiefTest.php, tests/TestMailable.php
in reference to #90
This lets mailthief intercept "Mailables"
note: My IDE sorted the imports and discarded the unused ones.
=> Allow mailer to intercept Mailable objects

readme.md
This PR adds a note to the Readme informing users that MailThief will no longer be updated beyond Laravel 5.5.
=> Update readme with note that app will remain at laravel 5.5.

.github/workflows/tests.yml, composer.json, tests/TestCase.php
- Add `php-7.3` and `php-7.4` version tests during GitHub Actions.
- It should be good to use the `\PHPUnit\Framework\TestCase` to easy to migrate stable `PHPUnit` versions easily.
=> Improvements for PHPUnit and PHP version tests
